### ISSUE TITLE
Allow to read filesystem of host

### ISSUE THREAD

**Issue by Bleuzen** [flathub/org.clementine_player.Clementine#2]
Hi, please add filesystem permission for the whole host filesystem. I have big files like music on another device (not on my ssd, where only my system and home are) and can't access it on this flatpak.

**Comment by TingPing** [comment]
> I have big files like music on another device

`xdg-user-dirs-update --set MUSIC /Any/other/path`

**Comment by TingPing** [comment]
If that isn't enough (like you have multiple music directories) you can just do `flatpak override --user --filesystem=/some/other/path/again org.clementine_player.Clementine`.

**Comment by FakeShemp** [comment]
@Bleuzen 
I used to have the same problem. Setting `XDG_MUSIC_DIR` to my external HDD was how I solved it, and really do believe it's the way to go. Allowing host access for a music player will very much compromise the sandbox unfortunately.

**Comment by Bleuzen** [comment]
@FakeShemp This is what I did too.
I still think that giving host access, at least read only, would be a good idea. Some people have multiple music folders on multiple devices and want it to 'just work'.
It is an open source music player.. what do you think for bad things that could happen when giving it read only permission for the whole filesystem?

**Comment by FakeShemp** [comment]
@Bleuzen Making it read only would not work as that would make tag editing, format conversion and playlist saving impossible.
As for what bad things could happen, you'll have to ask @TingPing, @alexlarsson or someone else who knows what they're talking about.

**Comment by TingPing** [comment]
Decoders are a pretty common security target for exploits since media files are commonly downloaded from untrustworthy places.

Now is it realistic that you will encounter one that targets your system? Probably not.

Does it make sense to give an application access to every password, private file, etc on your computer just in case?

**Comment by Bleuzen** [comment]
Probably not. To be honest, I'm not sure what would be the best. I mean it's normal that every program can access every file (at least in the users home). All the native apps do so, and it may be the easiest for new users, who want it to 'just work'. Some may see the option to have multiple music library directories in Clementine and wounder why it does not work. And for Clementine.. well, it's open source and Linux is not the biggest target for decoder exploited malware.
Iif it is better to give it host permissions or not may depend on the user.
I will do it for me, because I know where I'm clicking on.. but for others, maybe some 'more dumb' users.. maybe it's better to limit file system access.. but maybe they also are too dumb to figure out how to add another folder to their music library, where this flatpak has no permission for. Then they complain and say "this applications is bad and crap and.." blah..
Is this better? Not sure.
But to risk some private data.. (even if the risk is very tiny)
Is this better? Not sure either.

To be frank, after thinking some time about it, I lost my opinion. Both options have their good and bad sides.

Well, now we have this as and idea. I will let the maintainer of this flatpak decide.

**Comment by mr-falafel** [comment]
Just want to throw my opinion into this, which is that I think this issue makes the software hard to use. I don't want to change my XDG_MUSIC_DIR because other programs store files in it. most people don't know how to do this, either. I also don't want to have to launch Clementine from the command line with custom parameters, every time I use it. I guess I'm firmly in the wanting it to "just work" camp. 

Really, this is an issue for flatpak as a whole that needs to be answered sooner or later. I just find it particularly irritating with this software...
